### ISSUE TITLE
strings longer than 31 length result in "Cannot read property '_schema' of undefined"

### ISSUE THREAD

**Issue by DownyDude** [colyseus/schema#6] opened 2019-04-01 12:18 UTC
When using a long string value with a primitive type "string" inside a Custom Schema type I got this unexpected error in the client side when trying to listen to state changes with 

```
room.onJoin.add(function() { }) and room.state.players.onAdd = (player, key) => { } 
```

```
// Sample code to reproduce the error

const colyseus = require("colyseus")
const schema = require("@colyseus/schema")
const Schema = schema.Schema;
const MapSchema = schema.MapSchema;
//const ArraySchema = schema.ArraySchema;
const type = schema.type;

class Player extends Schema {
  constructor (id, str) {
    super();

    this.id = id;
    this.str = str;
  }
}
type('string')(Player.prototype, 'id');
type('string')(Player.prototype, 'str');


class MyState extends Schema {
    constructor () {
        super();

        this.players = new MapSchema();
    }
}
type({ map: Player })(MyState.prototype, 'players');


class MyRoom extends colyseus.Room {
    // When room is initialized
    onInit (options) {
        this.setState(new MyState());
    }

    // Checks if a new client is allowed to join. (default: `return true`)
    requestJoin (options, isNew) { }

    // Authorize client based on provided options before WebSocket handshake is complete
    onAuth (options) { }

    // When client successfully join the room
    onJoin (client, options, auth) {
        this.state.players[client.id] = new Player(1, 'test string'); //<-- This one works
        // uncomment this one bellow
        // this one rises the error
        //this.state.players[client.id] = new Player(1, 'Some Dummy And Very Long String Goes Here For Testing Purpose'); //<-- This one doesn't
    }

    // When a client sends a message
    onMessage (client, message) { }

    // When a client leaves the room
    onLeave (client, consented) { }

    // Cleanup callback, called after there are no more clients in the room. (see `autoDispose`)
    onDispose () { }
}
```

```
// in the index.js
const MyRoom = require("./MyRoom");
gameServer.register('my_room', MyRoom);
```

---------------------------

Good work by the way!
Thank you :)

**Comment by DownyDude** [comment] 2019-04-15 17:56
Any update?

**Comment by DownyDude** [comment] 2019-04-19 16:10
Is there any workaround?

**Comment by endel** [comment] 2019-04-19 17:02
Sorry the delay to reply @DownyDude, I'm going to fix this during this weekend. The problem is identifying the string length during decoding:

https://github.com/colyseus/schema/blob/5f7561a7d8dd3aeab0d98f56f817120abc3aede9/src/encoding/decode.ts#L144-L147

All decoders should be fixed (JavaScript, LUA, C#)

I'll suggest that you trim your strings to 31 length for now to prevent bugs, and soon this will be fixed!

**Comment by DownyDude** [comment] 2019-04-19 18:30
Great!
You're the man!
Good luck :)

**Closed** 2019-04-22 23:34 UTC
Labels: bug
